services:
    uptime-kuma:
        restart: unless-stopped
        ports:
            - 3001:3001
        volumes:
            - /mnt/portainer-compose-unpacker/stacks/uptime-kuma/uptime-kuma/data:/app/data
        container_name: uptime-kuma
        image: louislam/uptime-kuma:1
